#!/usr/bin/env python3
"""Draws the QRLeaderboard VMU icon (32x32, 16 colours): a QR-style code with
a gold star, and writes qr_icon.h (4bpp, high nibble = left pixel, ARGB4444)."""
import random, sys
from PIL import Image

PAL = [(0x10, 0x10, 0x28), (0xff, 0xff, 0xff), (0x20, 0x20, 0x40), (0xff, 0xcc, 0x33), (0xcc, 0x88, 0x11)]
W = 32
img = [[1] * W for _ in range(W)]           # white quiet area
for y in range(2, 30):
    for x in range(2, 30):
        img[y][x] = 1
random.seed(7)
for y in range(3, 29):                      # data modules
    for x in range(3, 29):
        img[y][x] = 0 if random.random() < 0.45 else 1
def finder(x0, y0):
    for y in range(7):
        for x in range(7):
            edge = x in (0, 6) or y in (0, 6)
            core = 2 <= x <= 4 and 2 <= y <= 4
            img[y0 + y][x0 + x] = 0 if edge or core else 1
    for i in range(-1, 8):                  # separator
        for (xx, yy) in ((x0 + i, y0 + 7), (x0 + 7, y0 + i), (x0 + i, y0 - 1), (x0 - 1, y0 + i)):
            if 2 <= xx < 30 and 2 <= yy < 30 and not (x0 <= xx < x0 + 7 and y0 <= yy < y0 + 7):
                img[yy][xx] = 1
finder(3, 3); finder(22, 3); finder(3, 22)
# star in the lower right
star = ["....#....", "...###...", "#########", ".#######.", "..#####..", ".###.###.", ".##...##."]
for j, row in enumerate(star):
    for i, c in enumerate(row):
        if c == '#': img[20 + j][20 + i] = 3
for j in range(-1, 8):
    for i in range(-1, 10):
        yy, xx = 20 + j, 20 + i
        if 0 <= yy < W and 0 <= xx < W and img[yy][xx] != 3 and (j in (-1, 7) or i in (-1, 9)):
            img[yy][xx] = 1
pal = [0xF000 | (r >> 4) << 8 | (g >> 4) << 4 | (b >> 4) for (r, g, b) in PAL] + [0] * (16 - len(PAL))
data = [img[y][x] << 4 | img[y][x + 1] for y in range(W) for x in range(0, W, 2)]
with open(sys.argv[1] if len(sys.argv) > 1 else 'qr_icon.h', 'w') as f:
    f.write("// Generated by make_icon.py: QRLeaderboard VMU icon, 32x32 4bpp\n#pragma once\n#include <stdint.h>\n\n")
    f.write("static const uint16_t QR_ICON_PAL[16] = {\n    " + ", ".join("0x%04X" % p for p in pal) + "\n};\n\n")
    f.write("static const uint8_t QR_ICON_DATA[512] = {\n")
    for i in range(0, 512, 16):
        f.write("    " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",\n")
    f.write("};\n")
if len(sys.argv) > 2:
    im = Image.new('RGB', (W, W))
    for y in range(W):
        for x in range(W): im.putpixel((x, y), PAL[img[y][x]])
    im.resize((256, 256), Image.NEAREST).save(sys.argv[2])
