#!/usr/bin/env python3
"""Draws the 32x32, 16-colour VMU save icon and writes vmu_icon.h
(4bpp pixels, high nibble = left pixel, and an ARGB4444 palette)."""
import sys
from PIL import Image

PAL = {                     # key: (r, g, b)
    'b': (0x22, 0x66, 0xee),  # upper sky
    '.': (0x55, 0xaa, 0xff),  # sky
    'w': (0xff, 0xff, 0xff),  # cloud / lane / plate
    'y': (0xff, 0xdd, 0x33),  # sun, blonde hair
    'g': (0x33, 0xcc, 0x44),  # palm leaves
    'G': (0x11, 0x77, 0x22),  # dark leaves, bushes
    't': (0x99, 0x66, 0x33),  # trunk
    's': (0xee, 0xdd, 0xaa),  # sand
    'r': (0x88, 0x88, 0x88),  # road
    'R': (0xee, 0x22, 0x22),  # car
    'D': (0x88, 0x11, 0x11),  # dark red
    'o': (0xff, 0x99, 0x22),  # tail lights
    'k': (0x22, 0x22, 0x22),  # tyres, dark hair
    'K': (0x55, 0x55, 0x55),  # shadow
}

W = H = 32
img = [['.'] * W for _ in range(H)]
HORIZON = 16

# Sky, sun, cloud
for y in range(0, 4):
    for x in range(W): img[y][x] = 'b'
for y in range(1, 6):
    for x in range(23, 30):
        if (x - 26) ** 2 + (y - 3) ** 2 <= 7: img[y][x] = 'y'
for x, y in [(12,7),(13,6),(14,6),(15,6),(16,7),(11,7),(17,7),(18,7),(13,7),(14,7),(15,7)]:
    img[y][x] = 'w'

# Ground: bushes on the horizon, sand, road with lane marks
for x in range(W): img[HORIZON][x] = 'G'
for y in range(HORIZON + 1, H):
    half = 1 + (y - HORIZON) * 0.95
    for x in range(W):
        d = abs(x + 0.5 - 16)
        img[y][x] = 'r' if d <= half else 's'
for y in range(HORIZON + 2, H, 1):
    if (y // 2) % 2 == 0:
        img[y][15] = img[y][16] = 'w'

# Palm tree on the left
trunk = [(3,31),(3,30),(4,29),(4,28),(4,27),(4,26),(5,25),(5,24),(5,23),(5,22),
         (5,21),(6,20),(6,19),(6,18),(6,17),(6,16),(7,15),(7,14),(7,13),(7,12),(7,11),(7,10),(8,9)]
for x, y in trunk:
    img[y][x] = 't'
    if y > 20: img[y][x + 1] = 't'
fronds = [
    [(8,8),(7,7),(6,6),(5,6),(4,6),(3,7),(2,8),(1,9)],
    [(8,8),(7,8),(6,8),(5,9),(4,10),(3,11)],
    [(8,8),(9,7),(10,6),(11,6),(12,6)],
    [(8,8),(9,8),(10,8),(11,9),(12,10),(13,11)],
    [(8,8),(8,7),(8,6),(7,5),(6,4)],
    [(8,8),(9,9),(9,10),(10,11)],
]
for f in fronds:
    for i, (x, y) in enumerate(f):
        img[y][x] = 'g' if i < len(f) - 2 else 'G'
        if i and i < len(f) - 1 and y + 1 < H and img[y + 1][x] in '.b':
            img[y + 1][x] = 'g' if i < 3 else 'G'
img[8][8] = 'G'

# Red convertible from behind (original drawing)
CAR = [
    ".....kk....yy...",
    "....kkkk..yyyy..",
    "..RRRRRRRRRRRR..",
    ".RRRRRRRRRRRRRR.",
    "RooRRRRRRRRRRooR",
    "RDDDDDDDDDDDDDDR",
    "RRRRRRwwwwRRRRRR",
    "kkkRRRRRRRRRRkkk",
    "kkkKKKKKKKKKKkkk",
]
cx, cy = 8, 22
for j, row in enumerate(CAR):
    for i, c in enumerate(row):
        if c != '.': img[cy + j][cx + i] = c

keys = list(PAL)
assert len(keys) <= 16
# Preview
out = Image.new('RGB', (W, H))
for y in range(H):
    for x in range(W):
        out.putpixel((x, y), PAL[img[y][x]])
out.resize((W * 8, H * 8), Image.NEAREST).save(sys.argv[1] if len(sys.argv) > 1 else 'icon_preview.png')

# Header
pal = [0xF000 | (r >> 4) << 8 | (g >> 4) << 4 | (b >> 4) for (r, g, b) in PAL.values()]
pal += [0] * (16 - len(pal))
data = []
for y in range(H):
    for x in range(0, W, 2):
        data.append(keys.index(img[y][x]) << 4 | keys.index(img[y][x + 1]))
with open(sys.argv[2] if len(sys.argv) > 2 else 'vmu_icon.h', 'w') as f:
    f.write("// Generated by tools/vmu_icon/make_icon.py: VMU save icon, 32x32 4bpp\n#pragma once\n#include <stdint.h>\n\n")
    f.write("static const uint16_t VMU_ICON_PAL[16] = {\n    " + ", ".join("0x%04X" % p for p in pal) + "\n};\n\n")
    f.write("static const uint8_t VMU_ICON_DATA[512] = {\n")
    for i in range(0, 512, 16):
        f.write("    " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",\n")
    f.write("};\n")
