#!/usr/bin/env python3
"""Draws the in-car view's bonnet as 4bpp pixel art and writes
src/main/dreamcast/pvr_hood.h. Original artwork in OutRun's style: banded
shading with mottled dithering like the car sprite's (short horizontal runs
of lighter and darker pixels, not a regular pattern), lit from above, and a
bonnet level across its width with a thin crease towards each side; the
front half rounds down towards the front edge. Straight sides angled out
towards the bottom of the screen so the bonnet reads as lying flat.

Headlight panel lines across the outer sections and a small yellow badge at
the front, after the Testarossa. The art runs HOOD_BELOW rows past the bottom
of the screen so the off-road bounce never opens a gap.

Colour indices (the renderer fills them each frame):
  0 transparent, 1-6 body shades from the car's palette (dark to light),
  8-14 badge: yellow, gold, pale cream, dark olive, black, dark gold, grey."""
import math, os, random, sys

W, H = 176, 20          # game pixels on screen (drawn 1.5x in the zoomed view)
BELOW = 2               # extra rows below the screen
TOP_W = 86              # width of the front edge (the Ferrari's width)

# Badge, 6x4: G gold, o dark olive, Y yellow, K black, g dark gold,
# P pale cream, s grey. Palette indices 8 upwards in BADGE_COLOURS order.
BADGE = [".GoGo.",
         "YKKgYg",
         "gYKKgY",
         "PPsPPP"]
BADGE_COLOURS = "YGPoKgs"
BADGE_Y = 2

def run_thresholds(width, rng):
    """Per-pixel dither thresholds for one row: runs of 1-4 pixels share a
    random threshold, which gives the car sprite's horizontal streaks."""
    out = []
    while len(out) < width:
        n = rng.choice((1, 2, 2, 3, 3, 4))
        out += [rng.random()] * n
    return out[:width]

def build():
    rng = random.Random(1986)
    img = [[0] * W for _ in range(H + BELOW)]
    for y in range(H + BELOW):
        # Straight sides, angled out towards the bottom of the screen so the
        # bonnet reads as lying flat in front of you
        f = y / (H - 1)
        half = (TOP_W + (W - TOP_W) * f) / 2
        thr = run_thresholds(W, rng)
        for x in range(W):
            dx = x + 0.5 - W / 2
            if abs(dx) > half: continue
            u = dx / half                       # -1 .. 1 across the bonnet
            a = abs(u)
            # Front edge: a very slight curve, with the corners turned down
            edge = 1.0 * a * a + 0.8 * (a ** 10)
            if y + 0.5 < edge: continue
            d_edge = y + 0.5 - edge
            # Level across its width: the same shade side to side (the
            # creases are just lines), shading only changes front to back
            s = 4.4
            # Thin crease towards each side (one pixel), a softer pixel outside it
            crease = abs(abs(dx) - 0.53 * half)
            if crease < 0.55:
                s = 1.6
            elif crease < 1.55 and abs(dx) > 0.53 * half:
                s -= 0.7
            # Along the bonnet: flat from the windscreen to about half way, then
            # rounding down towards the front. Lit from above: a light band
            # where the curve starts, then darker as the surface turns away,
            # and a darker lip on the very front.
            g = min(f, 1.0)                     # 0 = front edge, 1 = windscreen
            if g >= 0.5:
                s -= 0.5 * (g - 0.5) / 0.5      # flat rear half, a little darker near the glass
            else:
                c = (0.5 - g) / 0.5             # 0 at half way, 1 at the front
                if abs(dx) < 0.53 * half:      # highlight at the crest: straight across
                    s += 0.8 * math.exp(-((c - 0.2) / 0.13) ** 2)   # the centre, ending at the creases
                s -= 1.8 * c * c                                # turning away from the light
            if d_edge < 1.0:
                s -= 1.0
            # Mottling: a little noise in the shade itself, then the run dither
            s += (rng.random() - 0.5) * 0.5
            lo = math.floor(s); frac = s - lo
            v = max(1, min(6, lo + (1 if frac > thr[x] else 0)))
            if crease < 0.55:
                v = 2
            # Headlight panels: a straight panel line across each outer
            # section, from the crease out to the side
            if abs(dx) > 0.53 * half and y == 5:
                v = 2
            img[y][x] = v
    # Badge at the front of the centre (an original design; '.' = bonnet)
    for by, row in enumerate(BADGE):
        for bx, ch in enumerate(row):
            if ch != '.':
                img[BADGE_Y + by][W // 2 - 3 + bx] = BADGE_COLOURS.index(ch) + 8
    return img

def write_header(img, path):
    with open(path, "w") as f:
        f.write("// Generated by tools/hood/make_hood.py: in-car view bonnet, 4bpp indices\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("static const int HOOD_W = %d, HOOD_H = %d, HOOD_BELOW = %d;\n" % (W, H + BELOW, BELOW))
        f.write("static const uint8_t HOOD_PIXELS[%d] =\n{\n" % (W * (H + BELOW)))
        for row in img:
            f.write("    " + ",".join(str(v) for v in row) + ",\n")
        f.write("};\n")

if __name__ == "__main__":
    img = build()
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), "../../src/main/dreamcast/pvr_hood.h")
    write_header(img, out)
    for row in img:
        print("".join(" 123456789AB"[v] if v < 11 else "?" for v in row))
