#!/usr/bin/env python3
# Converts tools/vmu_anim/frames/frame_*.png (48x32, black and white) into
# src/main/dreamcast/vmu_anim.h for the VMU screen animation.
# Usage: python3 tools/vmu_anim/make_vmu_anim.py   (from the repo root)
import glob
from PIL import Image

frames = []
for path in sorted(glob.glob('tools/vmu_anim/frames/frame_*.png')):
    im = Image.open(path).convert('L')
    assert im.size == (48, 32), path + ': must be 48x32'
    b = bytearray(192)
    for y in range(32):
        for x in range(48):
            if im.getpixel((x, y)) < 128:          # dark pixel = bit set
                ry, rx = 31 - y, 47 - x            # VMU sits upside down in the controller
                b[ry * 6 + rx // 8] |= 0x80 >> (rx % 8)
    frames.append(b)

L = ['// VMU screen animation: 48x32, 1 bit per pixel (set = dark), 6 bytes per row.',
     '// Stored rotated 180 degrees, ready for vmu_draw_lcd() (a VMU sits upside',
     '// down in the controller). Generated by tools/vmu_anim/make_vmu_anim.py',
     '// from tools/vmu_anim/frames/*.png.', '#pragma once', '#include <stdint.h>', '',
     '#define VMU_ANIM_FRAMES %d' % len(frames), '',
     'static const uint8_t vmu_anim_data[VMU_ANIM_FRAMES][192] __attribute__((aligned(4))) = {']
for b in frames:
    L.append('    {')
    for r in range(0, 192, 12):
        L.append('        ' + ', '.join('0x%02x' % v for v in b[r:r + 12]) + ',')
    L.append('    },')
L.append('};')
open('src/main/dreamcast/vmu_anim.h', 'w').write('\n'.join(L) + '\n')
print('%d frames' % len(frames))
